/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '10/05/16 13:46' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 10/05/16 13:46
 */
public class RomanNumeral {
    public String add(String leftHand, String rightHand) {
        String leftHandSideAsIs = mapToI(leftHand);
        String rigtHandSideAsIs = mapToI(rightHand);
        String result = leftHandSideAsIs + rigtHandSideAsIs;
        return mapFromI(result);
    }

    private String mapFromI(String romanNumeral) {
        String result = romanNumeral.replace("IIIII","V");
        result = result.replace("VV","X");
        return result.replace("IIII","IV");
    }


    public String mapToI(String romanNumeral) {
        String result = romanNumeral.replace("IV","IIII");
        return result.replace("V","IIIII");
    }
}
